version: "3.8"

services:
  sqldb:
    image: mariadb
    container_name: sqldb
    volumes:
      - ./:/code
    ports:
      - "33666:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
